import data from '../assets/ApplicationData'

export default {
	gender: ['Male', 'Female', 'Non-binary'],
	race: ['American Indian or Alaskan Native', 'Asian / Pacific Islander', 'Black or African American', 'Black or African American', 'White / Caucasian', 'Mutliple ethnicity'],
	language: [],
	dietaryRestrictions: ['Vegetarian', 'Vegan', 'None'],
	shirtSize: ['Small', 'Medium', 'Large', 'X-Large', 'XX-Large', 'XXX-Large'],
	school: data.school,
	major: [],
	educationLevel: ['Undergraduate', 'Graduate', 'Post-Graduate'],
	interests: [],
	experience: [1, 2, 3, 4, 5],
	skills: [
		'Google Cloud',
		'AWS',
		'IBM Cloud',
		'Microsoft Azure',
		'Android',
		'IOS',
		'Web Developent',
		'API Development',
		'Machine Learning',
		'Virtual Reality',
		'Augmented Reality',
		'Cybersecurity',
		'Python',
		'Java',
		'Kotlin',
		'Objective-C',
		'Swift',
		'Javascript',
		'Go',
		'C/C++',
		'Linux',
		'Raspberry Pi',
		'Arduino'
	],
	awards: []
};
