apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: auburnhacks
  labels:
    app: auburnhacks
spec:
  backend:
    serviceName: apollo
    servicePort: 80
