apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: auburnhacks
  labels:
    app: auburnhacks
spec:
  tls:
  - secretName: secret
  rules:
  - host: auburnhacks.com
    http:
      paths:
          backend:
            serviceName: frontend
            servicePort: 80
