---
  apiVersion: v1
  kind: Service
  metadata:
    name: frontend
    labels:
      app: auburnhacks
  spec:
    type: NodePort
    selector:
      app: auburnhacks
      tier: web
    ports:
    - port: 80
      targetPort: 80