---
  apiVersion: v1
  kind: Service
  metadata:
    name: frontend
    labels:
      app: auburnhacks
  spec:
    type: NodePort
    selector:
      app: auburnhacks
      tier: web
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80
      - name: https
        protocol: TCP
        port: 443
        targetPort: 443