version: "3"
services:
  apollo:
    build: ./
    image: auburnhacks/apollo-server:latest
    restart: always
    network_mode: host
    ports:
      - "8383:8383"
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    network_mode: host
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: ${DB_HOST}
            port: 3306
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            migrations: true

#   mysql:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: prisma
#     volumes:
#       - mysql:/var/lib/mysql
# volumes:
#   mysql:
